# Generated by Django 4.0.5 on 2022-07-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacunasMaule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=50)),
                ('appaterno', models.CharField(max_length=50)),
                ('apmaterno', models.CharField(max_length=50)),
                ('profesion', models.CharField(max_length=50)),
            ],
        ),
    ]
