# Generated by Django 4.0.5 on 2022-07-11 22:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vacunasMaule', '0002_professional'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='professional',
            name='fechanacto',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
